### ISSUE TITLE
ros使用按钮button 发布目标位置点无法执行的情况

### ISSUE THREAD

**Issue by ju-mingyue** [6-robot/keras-frcnn#1]
@zhangwanjie 
您好，我在公众号内发现了咱们六部工坊，目前我也在学习ros相关的知识，因此有些问题需要向您请教。
我用手机下载的App来控制机器人运行，我在手机上创建一个按钮，我希望在手机端点击按钮，就可以把目标点发布给机器人，关于这方面您有什么建议或者想法呢？目前我对着一方面不是很明白，我想知道怎样做能够把手机内的按钮消息与发送目标点这一功能相结合，因为现在我查看到的话题内容只是true/false。希望得到您的回复。

**Comment by zhangwanjie** [comment]
你好，这个还需要看你还有没有后续需求。如果只发送一个目标点，可以用true/false类型的信号就可以了。如果将来还需要发送更多目标点，最好是发送一个二维坐标值。不管哪种数据类型，基本要实现的流程都差不多：
1、确定手机和机器人之间的通讯方式，是蓝牙还是无线网Wlan？
2、在手机端实现发送功能。
3、在机器人端实现接收功能，然后和手机进行数据发送/接收的测试，确定数据传输功能达成。
4、制定一个通讯协议，能够容纳需要发送的数据。如果是rue/false类型的信号最简单，直接判断有没有接收到数据就可以。
5、将要发送的数据按照协议从手机发送到机器人，确认机器人能够正确解析数值。
6、在机器人端实现一个导航的node，将接收到的坐标数值发送给Navigation进行导航。
基本就上面这些步骤。

**Comment by ju-mingyue** [comment]
@zhangwanjie 
您好，我的手机与机器人的通信方式为无线网通信，目前手机可以实现发送功能，但是电脑端收到的信息依旧是true/false，我使用data==true 进行判定，但是没有作用，我想添加三个按钮分别对应三个位置点，位置点信息包括xy坐标和角度信息。我还是不太明白怎样进行功能的绑定。
对于您说的true/false直接判断有没有接收到数据就可以，这个判定我试了很多，但是没能结合上。因此我希望您能再详细的指导我一下。
下面是我的两个程序：
程序一：
`
      #!/usr/bin/env python
      # -*- coding: utf-8 -*-
      
      import rospy
      from std_msgs.msg import Bool
      from geometry_msgs.msg import Pose, PoseWithCovarianceStamped, Point, Quaternion, Twist
      
      class Buttons():
	      def __init__(self):
		      rospy.init_node('button')
		      rospy.Subscriber("/button0",Bool,self.Callback1)
		      rospy.Subscriber("/button1",Bool,self.Callback2)
		      rospy.Subscriber("/button2",Bool,self.Callback3)
		      locations = dict() 
      
		      locations['1'] = Pose(Point(0.865, -0.245, 0.000),  Quaternion(0.000, 0.000, -0.561, 0.828))  
		      locations['2'] = Pose(Point(1.784, -5.144, 0.000),  Quaternion(0.000, 0.000, -0.645, 0.764))  
		      locations['3'] = Pose(Point(2.121, -7.942, 0.000), Quaternion(0.000, 0.000, 0.729, 0.685))  
      
	      def Callback1(self,Pose):
		      self.msg = Pose()
		      self.msg.Pose = Pose.locations['1']
		      global msg_pub
		      self.msg_pub.publish(self.msg)
		      self.send(event)
	      
	      def Callback2(self,Pose):
		      self.msg =Pose()
		      self.msg.Pose = Pose.locations['2']
		      global msg_pub
		      self.msg_pub.publish(self.msg)
		      self.send(event)
	      
	      def Callback3(self,Pose):
		      self.msg = Pose()
		      self.msg.Pose = Pose.locations['3']
		      global msg_pub
		      self.msg_pub.publish(self.msg)
		      self.send(event)
	      
	      def send(self,event)
		      self.msg_pub= rospy.Publisher('goal', Pose, queue_size=5)
      
      
      if __name__ == '__main__':
	      Buttons()
	      rospy.spin()
` 
我现在不知道这样是否可以实现，我是否需要把每一次callback都设定成目标点信息。
程序二：
`
        import roslib
        import rospy  
        import actionlib  
        from actionlib_msgs.msg import *  
        from geometry_msgs.msg import Pose, PoseWithCovarianceStamped, Point, Quaternion, Twist  
        from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal  
        from std_msgs.msg import Bool
        
        class  Navtest():
            def __init__(self):
                # 节点初始化 
                rospy.init_node('buttons', anonymous=True)  
                rospy.Subscriber("/mobile_base/events/button0",Bool,self.ButtonCallback)
                # 订阅move_base服务器的消息  
                self.move_base = actionlib.SimpleActionClient("move_base", MoveBaseAction)  
        
                rospy.loginfo("Waiting for move_base action server...")  
	        locations = dict()  
        
                locations['1'] = Pose(Point(0.865, -0.245, 0.000),  Quaternion(0.000, 0.000, -0.561, 0.828))  
                locations['2'] = Pose(Point(1.784, -5.144, 0.000),  Quaternion(0.000, 0.000, -0.645, 0.764))  
                locations['3'] = Pose(Point(2.121, -7.942, 0.000), Quaternion(0.000, 0.000, 0.729, 0.685))  
                locations['4'] = Pose(Point(1.508, -3.328, 0.000), Quaternion(0.000, 0.000, 0.748, 0.664))  
                locations['5'] = Pose(Point(-0.867, -2.354, 0.000), Quaternion(0.000, 0.000, 0.862, 0.508))  
                locations['6'] = Pose(Point(-0.037, 0.083, 0.000),   Quaternion(0.000, 0.000, 0.010, 1.000))  
        
        
                # 等待连接服务器，5s等待时间限制 
                while self.move_base.wait_for_server(rospy.Duration(5.0)) == 0:
                    rospy.loginfo("Connected to move base server")  
        
                #super( Navtest, self).__init__(*args))
            
            def ButtonCallback(self,data):
                print(data)
                
                if data==True:
                    location = 1
                    # 设定目标点  
                    #target = Pose(Point(-5.543, -4.779, 0.000), Quaternion(0.000, 0.000, 0.645, 0.764))  
                    self.goal = MoveBaseGoal()  
                    self.goal.target_pose.pose = locations[location] 
                    self.goal.target_pose.header.frame_id = 'map'  
                    self.goal.target_pose.header.stamp = rospy.Time.now() 
                    rospy.loginfo("Going to: " + str(target)) 
                    self.move(self.goal)
        
            def move(self,goal):
                
                # 向目标进发  
                self.move_base.send_goal(goal)  
        
                # 五分钟时间限制  
                self.finished_within_time = move_base.wait_for_result(rospy.Duration(300))   
        
                # 查看是否成功到达  
                if not finished_within_time:  
                    self.move_base.cancel_goal()  
                    rospy.loginfo("Timed out achieving goal")  
                else:  
                    state = self.move_base.get_state()  
                    if state == GoalStatus.SUCCEEDED:  
                        rospy.loginfo("Goal succeeded!")
                    else:  
            	        rospy.loginfo("Goal failed！ ")  
        
        if __name__ == '__main__': 
            m=Navtest()
            rospy.spin()
`
在第二个程序中，我按键后电脑端只能接收到true/false,在if判定处程序就不起作用了，我不清楚怎样去修改。
以及我的程序是否符合逻辑，希望您能指导我一下。非常感谢您。
